- NSX:
    - Controllers:
        - Controller 1:
            - id: nsxctrl01Hostname
              name: Hostname
            - id: nsxctrl01IP
              name: IP
            - id: nsxctrl01Netmask
              name: Netmask
            - id: nsxctrl01GW
              name: Gateway
            - id: nsxctrl01vcDatastoreName
              name: Datastore
        - Controller 2:
            - id: nsxctrl02Hostname
              name: Hostname
            - id: nsxctrl02IP
              name: IP
            - id: nsxctrl02Netmask
              name: Netmask
            - id: nsxctrl02GW
              name: Gateway
            - id: nsxctrl02vcDatastoreName
              name: Datastore
        - Controller 3:
            - id: nsxctrl03Hostname
              name: Hostname
            - id: nsxctrl03IP
              name: IP
            - id: nsxctrl03Netmask
              name: Netmask
            - id: nsxctrl03GW
              name: Gateway
            - id: nsxctrl03vcDatastoreName
              name: Datastore
    - Service Nodes:
        - Service Node 1:
            - id: nsxSN01Hostname
              name: Hostname
            - id: nsxSN01IP
              name: IP
            - id: nsxSN01Netmask
              name: Netmask
            - id: nsxSN01GW
              name: Gateway
            - id: nsxSN01vcDatastoreName
              name: Datastore
        - Service Node 2:
            - id: nsxSN02Hostname
              name: Hostname
            - id: nsxSN02IP
              name: IP
            - id: nsxSN02Netmask
              name: Netmask
            - id: nsxSN02GW
              name: Gateway
            - id: nsxSN02vcDatastoreName
              name: Datastore
    - Gateways:
        - Gateway 1:
            - id: nsxGW01Hostname
              name: Hostname
            - id: nsxGW01IP
              name: IP
            - id: nsxGW01Netmask
              name: Netmask
            - id: nsxGW01GW
              name: Gateway
            - id: nsxGW01vcDatastoreName
              name: Datastore
        - Gateway 2:
            - id: nsxGW02Hostname
              name: Hostname
            - id: nsxGW02IP
              name: IP
            - id: nsxGW02Netmask
              name: Netmask
            - id: nsxGW02GW
              name: Gateway
            - id: nsxGW02vcDatastoreName
              name: Datastore
    - Manager:
        - Manager:
            - id: nsxManagerHostname
              name: Hostname
            - id: nsxManagerIP
              name: IP
            - id: nsxManagerNetmask
              name: Netmask
            - id: nsxManagerGW
              name: Gateway
            - id: nsxManagervcDatastoreName
              name: Datastore
    - NSX Settings:
        - Controller Settings:
            - id: nsxCtrl1
              name: Hostname
            - id: nsxCtrl2
              name: IP
            - id: nsxCtrl3
              name: Netmask
            - id: nsxAdminUser
              name: Datastore
            - id: nsxAdminPass
              name: Gateway
            - id: tzName
              name: Transport Zone Name
            - id: gwServiceName
              name: Gateway Service Name
- SDDC:
    - Compute:
        - Compute 1:
            - id: computehostName
              name: Hostname
            - id: computeInternalIP
              name: IP
            - id: computeInternalNetmask
              name: Netmask
            - id: computeInternalGW
              name: Gateway
            - id: computevcDatastoreName
              name: Datastore
        - vCenter Settings:
            - id: vmwareVCHostIP
              name: vCenter
            - id: vmwareVCHostRootUser
              name: vCenter User
            - id: vmwareVCHostPassword
              name: vCenter Password
            - id: vmwareVolumeFolderName
              name: Volume Folder Name
            - id: vmwareGlanceDSName
              name: Glance Datastore Name
            - id: vmwareGlanceFolderName
              name: Glance Folder Name
            - id: vmwaredDataCenter
              name: vCenter Datacenter
            - id: vmwareVCClusterName
              name: vCenter Cluster
            - id: vmwareDSRegEx
              name: VMware RegEX
            - id: computeDriver
              name: Compute Driver
    - Controllers:
        - Controller 1:
            - id: vmos01hostName
              name: Hostname
            - id: vmos01InternalIP
              name: IP
            - id: vmos01InternalNetmask
              name: Netmask
            - id: vmos01InternalGW
              name: Gateway
            - id: vmos01vcDatastoreName
              name: Datastore
        - Controller 2:
            - id: vmos02hostName
              name: Hostname
            - id: vmos02InternalIP
              name: IP
            - id: vmos02InternalNetmask
              name: Netmask
            - id: vmos02InternalGW
              name: Gateway
            - id: vmos2vcDatastoreName
              name: Datastore
    - DHCP Agents:
        - DHCP Agent 1:
            - id: dhcp01hostName
              name: Hostname
            - id: dhcp01InternalIP
              name: IP
            - id: dhcp01InternalNetmask
              name: Netmask
            - id: dhcp01InternalGW
              name: Gateway
            - id: dhcp01vcDatastoreName
              name: Datastore
        - DHCP Agent 2:
            - id: dhcp02hostName
              name: Hostname
            - id: dhcp02InternalIP
              name: IP
            - id: dhcp02InternalNetmask
              name: Netmask
            - id: dhcp02InternalGW
              name: Gateway
            - id: dhcp02vcDatastoreName
              name: Datastore
        - Settings:
            - id: dhcp_agents_per_net
              name: Number of DHCP Agents Per Network
            - id: resync_interval
              name: Resync Interval
            - id: dhcp_domain
              name: DHCP Domain
    - Load Balancers:
        - Load Balancer 1:
            - id: lb01hostName
              name: Hostname
            - id: lb01InternalIP
              name: Internal IP
            - id: lb01InternalNetmask
              name: Internal Netmask
            - id: lb01InternalGW
              name: Internal Gateway
            - id: lb01PublicIP
              name: Public IP
            - id: lb01PublicNetmask
              name: Public Netmask
            - id: lb01PublicGW
              name: Public Gateway
            - id: lb01vcDatastoreName
              name: Datastore
        - Load Balancer 2:
            - id: lb02hostName
              name: Hostname
            - id: lb02InternalIP
              name: Internal IP
            - id: lb02InternalNetmask
              name: Internal Netmask
            - id: lb02InternalGW
              name: Internal Gateway
            - id: lb02PublicIP
              name: Public IP
            - id: lb02PublicNetmask
              name: Public Netmask
            - id: lb02PublicGW
              name: Public Gateway
            - id: lb02vcDatastoreName
              name: Datastore
        - Settings:
            - id: publicVIP
              name: Public Virtual IP 
            - id: internalVIP
              name: Internal Virtual IP
            - id: lbNotifyEmailFrom
              name: Address To Send Alerts From
            - id: lbNotifyEmailAddress
              name: Address To Send Alerts To
            - id: smtp_server
              name: SMTP Server
    - Memcache:
        - Memcache 1:
            - id: memcache01hostName
              name: Hostname
            - id: memcache01InternalIP
              name: IP
            - id: memcache01InternalNetmask
              name: Netmask
            - id: memcache01InternalGW
              name: Gateway
            - id: memcache01vcDatastoreName
              name: Datastore
        - Memcache 2:
            - id: memcache02hostName
              name: Hostname
            - id: memcache02InternalIP
              name: IP
            - id: memcache02InternalNetmask
              name: Netmask
            - id: memcache02InternalGW
              name: Gateway
            - id: memcache02vcDatastoreName
              name: Datastore
        - Settings:
            - id: cacheMemAllocate
              name: Memory Allocated to Memcache
    - MQ:
        - MQ 1:
            - id: mq01hostName
              name: Hostname
            - id: mq01InternalIP
              name: IP
            - id: mq01InternalNetmask
              name: Netmask
            - id: mq01InternalGW
              name: Gateway
            - id: mq01vcDatastoreName
              name: Datastore
        - MQ 2:
            - id: mq02hostName
              name: Hostname
            - id: mq02InternalIP
              name: IP
            - id: mq02InternalNetmask
              name: Netmask
            - id: mq02InternalGW
              name: Gateway
            - id: mq02vcDatastoreName
              name: Datastore
        - Settings:
            - id: rabbitUserID
              name: MQ User
            - id: rabbitPassword
              name: MQ Password
    - SQL Servers:
        - SQL Server 1:
            - id: sql01hostName
              name: Hostname
            - id: sql01InternalIP
              name: IP
            - id: sql01InternalNetmask
              name: Netmask
            - id: sql01InternalGW
              name: Gateway
            - id: sql01vcDatastoreName
              name: Datastore
        - SQL Server 2:
            - id: sql02hostName
              name: Hostname
            - id: sql02InternalIP
              name: IP
            - id: sql02InternalNetmask
              name: Netmask
            - id: sql02InternalGW
              name: Gateway
            - id: sql02vcDatastoreName
              name: Datastore
        - SQL Server 3:
            - id: sql03hostName
              name: Hostname
            - id: sql03InternalIP
              name: IP
            - id: sql03InternalNetmask
              name: Netmask
            - id: sql03InternalGW
              name: Gateway
            - id: sql03vcDatastoreName
              name: Datastore
        - Database Users:
            - id: sqlRootUser
              name: Root User
            - id: cinderDBUser
              name: Cinder User
            - id: glanceDBUser
              name: Glance User
            - id: keystoneDBUser
              name: Keystone User
            - id: neutronDBUser
              name: Neutron User
            - id: novaDBUser
              name: Nova User
        - Database Passwords:
            - id: sqlRootPassword
              name: Root Password
            - id: cinderDBPassword
              name: Cinder Password
            - id: glanceDBPassword
              name: Glance Password
            - id: keystoneDBPassword
              name: Keystone Password
            - id: neutronDBPassword
              name: Neutron Password
            - id: novaDBPassword
              name: Nova Password
    - OpenStack Settings:
        - Service Users:
            - id: adminTenantName
              name: Admin Tenant User
            - id: cinderAdminUser
              name: Cinder Admin User
            - id: glanceAdminUser
              name: Glance Admin User
            - id: keystoneAdminUser
              name: Keystone Admin User
            - id: neutronAdminUser
              name: Neutron Admin User
            - id: novaAdminUser
              name: Nova Admin User
        - Service Passwords:
            - id: adminTenantPassword
              name: Admin Tenant Password
            - id: cinderAdminPassword
              name: Cinder Admin Password
            - id: glanceAdminPassword
              name: Glance Admin Password
            - id: keystoneAdminPassword
              name: Keystone Admin Password
            - id: neutronAdminPassword
              name: Neutron Admin Password
            - id: novaAdminPassword
              name: Nova Admin Password
        - Miscellaneous:
            - id: regionName
              name: Region Name
            - id: cpuAllocRatio
              name: CPU Allocation Ratio
            - id: ramAllocRatio
              name: RAM Allocation Ratio
            - id: metadataSharedSecret
              name: Metadata Shared Secret
            - id: keystoneAdminToken
              name: Keystone Admin Token
            - id: tokenExpirationTime
              name: Token Expiration Time
- Global:
    - Settings:
        - Settings:
            - id: dnsServer1
              name: DNS Server 1
            - id: dnsServer2
              name: DNS Server 2
            - id: ntpServer01
              name: NTP Server 1
            - id: ntpServer02
              name: NTP Server 2
            - id: dnsDomain
              name: DNS Domain
    - Management vCenter:
        - vCenter:
            - id: mgmtvCenterIP
              name: vCenter IP
            - id: mgmtRootUser
              name: vCenter User
            - id: mgmtRootPassword
              name: vCenter Password
            - id: mgmtDataCenterName
              name: vCenter Datacenter
            - id: mgmtClusterName
              name: Management vCenter Cluster
            - id: internalPortGroup
              name: vCenter Internal Port Group
            - id: publicPortGroup
              name: vCenter Public Port Group
            - id: GWExternalPortGroup
              name: vCenter Port Group for Gateway External Interface
